//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit17
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductData
    {
        public int Id { get; set; }
        public string email { get; set; }
        public string productCode { get; set; }
        public string nameProduct { get; set; }
    }
}
